In [1]:
import shutup

In [2]:
shutup.mute_warnings()

In [3]:
import hypernetx as hnx

In [4]:
hg = hnx.Hypergraph( [ {1,2}, {1,2}, {1,2,3} ] )

In [5]:
hg = hnx.Hypergraph( {'e1':[1,2], 'e2':[1,2], 'e3':[1,2,3]} )

In [11]:
hg.adjacency_matrix().toarray()

array([[0, 1, 1],
       [1, 0, 1],
       [1, 1, 0]])

In [13]:
d = {
    'e1':{
        1: {'w':0.5, 'name': 'related_to'},
        2: {'w':0.1, 'name': 'related_to', 'startdate': '05.13.2020'}
        },
     'e2':{ 
        1: {'w':0.52, 'name': 'owned_by'},
        2: {'w':0.2}
        },
     'e3':{
        1: {'w':0.5, 'name': 'related_to'},
        2: {'w':0.2, 'name': 'owner_of'},
        3: {'w':1, 'type': 'relationship'}
        }
    }

In [14]:
hg = hnx.Hypergraph(d, cell_weight_col='w')

In [8]:
import numpy as np

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
Out[8]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
In[8]

'import numpy as np\n\nnp.arange(10)'

In [11]:
print(_)

import numpy as np

np.arange(10)


In [12]:
_

'import numpy as np\n\nnp.arange(10)'

In [13]:
%history

import shutup
shutup.mute_warnings()
import hypernetx as hnx
hg = hnx.Hypergraph( [ {1,2}, {1,2}, {1,2,3} ] )
hg = hnx.Hypergraph( {'e1':[1,2], 'e2':[1,2], 'e3':[1,2,3]} )
import numpy as np

numpy.arange(10)
import numpy as np

numpy.arange(10)
import numpy as np

np.arange(10)
Out[8]
In[8]
print(_)
_
%history


In [14]:
    help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [15]:
import inspect

In [20]:
inspect.getmembers(hnx, inspect.ismodule)

[('algorithms',
  <module 'hypernetx.algorithms' from '/Users/arnoudb/hypergraphs/.venv/lib/python3.12/site-packages/hypernetx/algorithms/__init__.py'>),
 ('classes',
  <module 'hypernetx.classes' from '/Users/arnoudb/hypergraphs/.venv/lib/python3.12/site-packages/hypernetx/classes/__init__.py'>),
 ('drawing',
  <module 'hypernetx.drawing' from '/Users/arnoudb/hypergraphs/.venv/lib/python3.12/site-packages/hypernetx/drawing/__init__.py'>),
 ('exception',
  <module 'hypernetx.exception' from '/Users/arnoudb/hypergraphs/.venv/lib/python3.12/site-packages/hypernetx/exception.py'>),
 ('read_write',
  <module 'hypernetx.read_write' from '/Users/arnoudb/hypergraphs/.venv/lib/python3.12/site-packages/hypernetx/read_write.py'>),
 ('reports',
  <module 'hypernetx.reports' from '/Users/arnoudb/hypergraphs/.venv/lib/python3.12/site-packages/hypernetx/reports/__init__.py'>),
 ('utils',
  <module 'hypernetx.utils' from '/Users/arnoudb/hypergraphs/.venv/lib/python3.12/site-packages/hypernetx/utils/_

In [21]:
inspect.getmembers(hnx, inspect.isclass)

[('DefaultOrderedDict', hypernetx.utils.extras.DefaultOrderedDict),
 ('EntitySet', hypernetx.classes.entityset.EntitySet),
 ('GeneData', hypernetx.utils.toys.gene_data.GeneData),
 ('HNXCount', hypernetx.utils.extras.HNXCount),
 ('HarryPotter', hypernetx.utils.toys.harrypotter.HarryPotter),
 ('HyperNetXError', hypernetx.exception.HyperNetXError),
 ('HyperNetXException', hypernetx.exception.HyperNetXException),
 ('HyperNetXNotImplementedError',
  hypernetx.exception.HyperNetXNotImplementedError),
 ('Hypergraph', hypernetx.classes.hypergraph.Hypergraph),
 ('LesMis', hypernetx.utils.toys.lesmis.LesMis),
 ('TransmissionProblem',
  hypernetx.utils.toys.transmission_problem.TransmissionProblem)]

In [22]:
inspect.getmembers(hnx, inspect.isfunction)

[('Gillespie_SIR',
  <function hypernetx.algorithms.contagion.Gillespie_SIR(H, tau, gamma, transmission_function=<function threshold at 0x14d11f240>, initial_infecteds=None, initial_recovereds=None, rho=None, tmin=0, tmax=inf, **args)>),
 ('Gillespie_SIS',
  <function hypernetx.algorithms.contagion.Gillespie_SIS(H, tau, gamma, transmission_function=<function threshold at 0x14d11f240>, initial_infecteds=None, rho=None, tmin=0, tmax=inf, return_full_data=False, sim_kwargs=None, **args)>),
 ('add_to_column',
  <function hypernetx.algorithms.homology_mod2.add_to_column(M, i, j)>),
 ('add_to_row',
  <function hypernetx.algorithms.homology_mod2.add_to_row(M, i, j)>),
 ('betti', <function hypernetx.algorithms.homology_mod2.betti(bd, k=None)>),
 ('betti_numbers',
  <function hypernetx.algorithms.homology_mod2.betti_numbers(h, k=None)>),
 ('bkMatrix',
  <function hypernetx.algorithms.homology_mod2.bkMatrix(km1basis, kbasis)>),
 ('book_tour',
  <function hypernetx.utils.toys.lesmis.book_tour(df,

In [24]:
inspect.getmembers(hnx.Hypergraph, inspect.ismethod)

[('from_bipartite',
  <bound method Hypergraph.from_bipartite of <class 'hypernetx.classes.hypergraph.Hypergraph'>>),
 ('from_incidence_dataframe',
  <bound method Hypergraph.from_incidence_dataframe of <class 'hypernetx.classes.hypergraph.Hypergraph'>>),
 ('from_incidence_matrix',
  <bound method Hypergraph.from_incidence_matrix of <class 'hypernetx.classes.hypergraph.Hypergraph'>>),
 ('from_numpy_array',
  <bound method Hypergraph.from_numpy_array of <class 'hypernetx.classes.hypergraph.Hypergraph'>>)]

In [26]:
inspect.getmembers(hnx.Hypergraph, inspect.is)

[('__contains__',
  <function hypernetx.classes.hypergraph.Hypergraph.__contains__(self, item)>),
 ('__getitem__',
  <function hypernetx.classes.hypergraph.Hypergraph.__getitem__(self, node)>),
 ('__init__',
  <function hypernetx.classes.hypergraph.Hypergraph.__init__(self, setsystem: 'Optional[pd.DataFrame | np.ndarray | Mapping[T, Iterable[T]] | Iterable[Iterable[T]] | Mapping[T, Mapping[T, Mapping[str, Any]]]]' = None, edge_col: 'str | int' = 0, node_col: 'str | int' = 1, cell_weight_col: 'Optional[str | int]' = 'cell_weights', cell_weights: 'Sequence[float] | float' = 1.0, cell_properties: 'Optional[Sequence[str | int] | Mapping[T, Mapping[T, Mapping[str, Any]]]]' = None, misc_cell_properties_col: 'Optional[str | int]' = None, aggregateby: 'str | dict[str, str]' = 'first', edge_properties: 'Optional[pd.DataFrame | dict[T, dict[Any, Any]]]' = None, node_properties: 'Optional[pd.DataFrame | dict[T, dict[Any, Any]]]' = None, properties: 'Optional[pd.DataFrame | dict[T, dict[Any, Any]]

In [29]:
classes = inspect.getmembers(hnx, inspect.isclass)

In [48]:
classes

[('DefaultOrderedDict', hypernetx.utils.extras.DefaultOrderedDict),
 ('EntitySet', hypernetx.classes.entityset.EntitySet),
 ('GeneData', hypernetx.utils.toys.gene_data.GeneData),
 ('HNXCount', hypernetx.utils.extras.HNXCount),
 ('HarryPotter', hypernetx.utils.toys.harrypotter.HarryPotter),
 ('HyperNetXError', hypernetx.exception.HyperNetXError),
 ('HyperNetXException', hypernetx.exception.HyperNetXException),
 ('HyperNetXNotImplementedError',
  hypernetx.exception.HyperNetXNotImplementedError),
 ('Hypergraph', hypernetx.classes.hypergraph.Hypergraph),
 ('LesMis', hypernetx.utils.toys.lesmis.LesMis),
 ('TransmissionProblem',
  hypernetx.utils.toys.transmission_problem.TransmissionProblem)]

In [53]:
[ c for c in classes if c == 'Hypergraph' ]

[]

In [ ]:
ins